const mongoose = require("mongoose");
require("dotenv").config({ path: require("path").join(__dirname, "..", "..", ".env") });

const foods = [
  // Frutas
  { name: "Manzana", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 52, protein: 0.3, fat: 0.2, saturatedFat: 0, carbs: 14, sugar: 10, fiber: 2.4, sodium: 1 },
    nutritionalScore: 9.5, tags: ["fruta", "natural"] },
  { name: "Banana", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 89, protein: 1.1, fat: 0.3, saturatedFat: 0.1, carbs: 23, sugar: 12, fiber: 2.6, sodium: 1 },
    nutritionalScore: 8.5, tags: ["fruta", "natural"] },
  { name: "Naranja", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 47, protein: 0.9, fat: 0.1, saturatedFat: 0, carbs: 12, sugar: 9, fiber: 2.4, sodium: 0 },
    nutritionalScore: 9.5, tags: ["fruta", "natural", "vitamina c"] },
  { name: "Frutilla", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 32, protein: 0.7, fat: 0.3, saturatedFat: 0, carbs: 7.7, sugar: 4.9, fiber: 2, sodium: 1 },
    nutritionalScore: 9.5, tags: ["fruta", "natural"] },
  { name: "Uva", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 69, protein: 0.7, fat: 0.2, saturatedFat: 0, carbs: 18, sugar: 16, fiber: 0.9, sodium: 2 },
    nutritionalScore: 7.5, tags: ["fruta", "natural"] },
  { name: "Pera", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 57, protein: 0.4, fat: 0.1, saturatedFat: 0, carbs: 15, sugar: 10, fiber: 3.1, sodium: 1 },
    nutritionalScore: 9, tags: ["fruta", "natural"] },
  { name: "Durazno", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 39, protein: 0.9, fat: 0.3, saturatedFat: 0, carbs: 10, sugar: 8, fiber: 1.5, sodium: 0 },
    nutritionalScore: 9, tags: ["fruta", "natural"] },

  // Verduras
  { name: "Espinaca", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 23, protein: 2.9, fat: 0.4, saturatedFat: 0, carbs: 3.6, sugar: 0.4, fiber: 2.2, sodium: 79 },
    nutritionalScore: 10, tags: ["verdura", "hoja verde"] },
  { name: "BrÃ³coli", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 34, protein: 2.8, fat: 0.4, saturatedFat: 0, carbs: 6.6, sugar: 1.7, fiber: 2.6, sodium: 33 },
    nutritionalScore: 10, tags: ["verdura"] },
  { name: "Zanahoria", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 41, protein: 0.9, fat: 0.2, saturatedFat: 0, carbs: 9.6, sugar: 4.7, fiber: 2.8, sodium: 69 },
    nutritionalScore: 9, tags: ["verdura", "vitamina a"] },
  { name: "Tomate", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 18, protein: 0.9, fat: 0.2, saturatedFat: 0, carbs: 3.9, sugar: 2.6, fiber: 1.2, sodium: 5 },
    nutritionalScore: 9.5, tags: ["verdura"] },
  { name: "Papa", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 77, protein: 2, fat: 0.1, saturatedFat: 0, carbs: 17, sugar: 0.8, fiber: 2.2, sodium: 6 },
    nutritionalScore: 7.5, tags: ["verdura", "almidon"] },
  { name: "Batata", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 86, protein: 1.6, fat: 0.1, saturatedFat: 0, carbs: 20, sugar: 4.2, fiber: 3, sodium: 55 },
    nutritionalScore: 8.5, tags: ["verdura", "almidon"] },
  { name: "Zapallito", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 17, protein: 1.2, fat: 0.3, saturatedFat: 0, carbs: 3.1, sugar: 2.5, fiber: 1, sodium: 8 },
    nutritionalScore: 9.5, tags: ["verdura"] },
  { name: "Lechuga", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 15, protein: 1.4, fat: 0.2, saturatedFat: 0, carbs: 2.9, sugar: 0.8, fiber: 1.3, sodium: 28 },
    nutritionalScore: 10, tags: ["verdura", "hoja verde"] },
  { name: "Cebolla", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 40, protein: 1.1, fat: 0.1, saturatedFat: 0, carbs: 9.3, sugar: 4.2, fiber: 1.7, sodium: 4 },
    nutritionalScore: 8.5, tags: ["verdura"] },
  { name: "MorrÃ³n rojo", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 31, protein: 1, fat: 0.3, saturatedFat: 0, carbs: 6, sugar: 4.2, fiber: 2.1, sodium: 4 },
    nutritionalScore: 9.5, tags: ["verdura", "vitamina c"] },

  // ProteÃ­nas
  { name: "Pechuga de pollo", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 165, protein: 31, fat: 3.6, saturatedFat: 1, carbs: 0, sugar: 0, fiber: 0, sodium: 74 },
    nutritionalScore: 9, tags: ["carne", "proteina", "magra"] },
  { name: "Carne de res magra", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 250, protein: 26, fat: 15, saturatedFat: 6, carbs: 0, sugar: 0, fiber: 0, sodium: 72 },
    nutritionalScore: 6.5, tags: ["carne", "proteina"] },
  { name: "Pescado blanco (merluza)", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 90, protein: 19, fat: 1, saturatedFat: 0.2, carbs: 0, sugar: 0, fiber: 0, sodium: 60 },
    nutritionalScore: 9.5, tags: ["pescado", "proteina", "magra"] },
  { name: "SalmÃ³n", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 208, protein: 20, fat: 13, saturatedFat: 3, carbs: 0, sugar: 0, fiber: 0, sodium: 59 },
    nutritionalScore: 8.5, tags: ["pescado", "proteina", "omega3"] },
  { name: "AtÃºn en lata", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 116, protein: 26, fat: 1, saturatedFat: 0.3, carbs: 0, sugar: 0, fiber: 0, sodium: 250 },
    nutritionalScore: 8.5, tags: ["pescado", "proteina", "enlatado"] },
  { name: "Huevo", brand: "", servingSize: 50, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 143, protein: 12.6, fat: 9.5, saturatedFat: 3.1, carbs: 0.7, sugar: 0.4, fiber: 0, sodium: 124 },
    nutritionalScore: 8.5, tags: ["huevo", "proteina"] },
  { name: "Tofu", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 76, protein: 8, fat: 4.8, saturatedFat: 0.7, carbs: 1.9, sugar: 0.6, fiber: 0.3, sodium: 7 },
    nutritionalScore: 9, tags: ["vegano", "proteina", "soja"] },
  { name: "Lentejas (cocidas)", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 116, protein: 9, fat: 0.4, saturatedFat: 0, carbs: 20, sugar: 1.8, fiber: 7.9, sodium: 2 },
    nutritionalScore: 9.5, tags: ["legumbre", "proteina vegetal"] },
  { name: "Garbanzos (cocidos)", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 164, protein: 8.9, fat: 2.6, saturatedFat: 0.3, carbs: 27, sugar: 4.8, fiber: 7.6, sodium: 7 },
    nutritionalScore: 9, tags: ["legumbre", "proteina vegetal"] },
  { name: "Pechuga de pavo", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 135, protein: 30, fat: 1, saturatedFat: 0.2, carbs: 0, sugar: 0, fiber: 0, sodium: 68 },
    nutritionalScore: 9, tags: ["carne", "proteina", "magra"] },

  // LÃ¡cteos
  { name: "Yogur natural", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 61, protein: 3.5, fat: 3.3, saturatedFat: 2.1, carbs: 4.7, sugar: 4.7, fiber: 0, sodium: 46 },
    nutritionalScore: 8, tags: ["lacteo", "proteina"] },
  { name: "Queso crema", brand: "", servingSize: 30, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 342, protein: 6, fat: 34, saturatedFat: 21, carbs: 4, sugar: 3.5, fiber: 0, sodium: 340 },
    nutritionalScore: 4.5, tags: ["lacteo", "queso"] },
  { name: "Queso mozzarella", brand: "", servingSize: 30, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 280, protein: 28, fat: 17, saturatedFat: 10, carbs: 3.1, sugar: 1, fiber: 0, sodium: 627 },
    nutritionalScore: 6, tags: ["lacteo", "queso"] },
  { name: "Leche descremada", brand: "", servingSize: 200, servingUnit: "ml", category: "search",
    nutritionPer100g: { calories: 34, protein: 3.4, fat: 0.1, saturatedFat: 0, carbs: 5, sugar: 5, fiber: 0, sodium: 40 },
    nutritionalScore: 8, tags: ["lacteo", "leche"] },
  { name: "Leche entera", brand: "", servingSize: 200, servingUnit: "ml", category: "search",
    nutritionPer100g: { calories: 61, protein: 3.2, fat: 3.3, saturatedFat: 1.9, carbs: 4.8, sugar: 5, fiber: 0, sodium: 43 },
    nutritionalScore: 7, tags: ["lacteo", "leche"] },

  // Granos y carbohidratos
  { name: "Arroz blanco", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 130, protein: 2.7, fat: 0.3, saturatedFat: 0.1, carbs: 28, sugar: 0.1, fiber: 0.4, sodium: 1 },
    nutritionalScore: 5.5, tags: ["grano", "almidon"] },
  { name: "Arroz integral", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 111, protein: 2.6, fat: 0.9, saturatedFat: 0.2, carbs: 23, sugar: 0.4, fiber: 1.8, sodium: 5 },
    nutritionalScore: 7.5, tags: ["grano", "integral"] },
  { name: "Avena", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 389, protein: 16.9, fat: 6.9, saturatedFat: 1.2, carbs: 66, sugar: 0, fiber: 10.6, sodium: 2 },
    nutritionalScore: 8.5, tags: ["grano", "integral", "fibra"] },
  { name: "Quinoa", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 120, protein: 4.4, fat: 1.9, saturatedFat: 0.2, carbs: 21, sugar: 0.9, fiber: 2.8, sodium: 7 },
    nutritionalScore: 8.5, tags: ["grano", "integral", "proteina vegetal"] },
  { name: "Pan integral", brand: "", servingSize: 30, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 247, protein: 13, fat: 3.4, saturatedFat: 0.5, carbs: 41, sugar: 5, fiber: 7, sodium: 500 },
    nutritionalScore: 7, tags: ["pan", "integral"] },
  { name: "Pan blanco", brand: "", servingSize: 30, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 265, protein: 9, fat: 3.2, saturatedFat: 0.5, carbs: 49, sugar: 5, fiber: 2.7, sodium: 490 },
    nutritionalScore: 5, tags: ["pan"] },
  { name: "Pasta integral", brand: "", servingSize: 80, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 124, protein: 5.3, fat: 0.9, saturatedFat: 0.2, carbs: 25, sugar: 0.6, fiber: 3, sodium: 2 },
    nutritionalScore: 7, tags: ["pasta", "integral"] },
  { name: "Fideos", brand: "", servingSize: 80, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 131, protein: 4.6, fat: 0.7, saturatedFat: 0.1, carbs: 26, sugar: 0.6, fiber: 1.5, sodium: 2 },
    nutritionalScore: 5.5, tags: ["pasta"] },

  // Frutos secos y semillas
  { name: "Almendras", brand: "", servingSize: 30, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 579, protein: 21, fat: 50, saturatedFat: 3.9, carbs: 22, sugar: 4.4, fiber: 12.5, sodium: 1 },
    nutritionalScore: 8, tags: ["fruto seco", "grasa saludable"] },
  { name: "Nueces", brand: "", servingSize: 30, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 654, protein: 15, fat: 65, saturatedFat: 6.1, carbs: 14, sugar: 2.6, fiber: 6.7, sodium: 2 },
    nutritionalScore: 7.5, tags: ["fruto seco", "grasa saludable", "omega3"] },
  { name: "ManÃ­", brand: "", servingSize: 30, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 567, protein: 26, fat: 49, saturatedFat: 6.9, carbs: 16, sugar: 4.7, fiber: 8.5, sodium: 18 },
    nutritionalScore: 7.5, tags: ["fruto seco", "proteina vegetal"] },
  { name: "ChÃ­a", brand: "", servingSize: 15, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 486, protein: 17, fat: 31, saturatedFat: 3.3, carbs: 42, sugar: 0, fiber: 34, sodium: 16 },
    nutritionalScore: 9, tags: ["semilla", "fibra", "omega3"] },
  { name: "Palta", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 160, protein: 2, fat: 15, saturatedFat: 2.1, carbs: 9, sugar: 0.7, fiber: 6.7, sodium: 7 },
    nutritionalScore: 8.5, tags: ["grasa saludable", "fruta"] },

  // Aceites y grasas
  { name: "Aceite de oliva", brand: "", servingSize: 10, servingUnit: "ml", category: "search",
    nutritionPer100g: { calories: 884, protein: 0, fat: 100, saturatedFat: 14, carbs: 0, sugar: 0, fiber: 0, sodium: 0 },
    nutritionalScore: 7, tags: ["aceite", "grasa saludable"] },
  { name: "Manteca", brand: "", servingSize: 10, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 717, protein: 0.9, fat: 81, saturatedFat: 51, carbs: 0.1, sugar: 0.1, fiber: 0, sodium: 11 },
    nutritionalScore: 3, tags: ["grasa"] },

  // Bebidas
  { name: "Gaseosa cola", brand: "", servingSize: 350, servingUnit: "ml", category: "search",
    nutritionPer100g: { calories: 42, protein: 0, fat: 0, saturatedFat: 0, carbs: 10.6, sugar: 10.6, fiber: 0, sodium: 4 },
    nutritionalScore: 1.5, tags: ["bebida", "azucar"] },
  { name: "Jugo de naranja natural", brand: "", servingSize: 250, servingUnit: "ml", category: "search",
    nutritionPer100g: { calories: 45, protein: 0.7, fat: 0.2, saturatedFat: 0, carbs: 10, sugar: 8, fiber: 0.2, sodium: 1 },
    nutritionalScore: 7, tags: ["bebida", "vitamina c"] },
  { name: "Agua mineral", brand: "", servingSize: 500, servingUnit: "ml", category: "search",
    nutritionPer100g: { calories: 0, protein: 0, fat: 0, saturatedFat: 0, carbs: 0, sugar: 0, fiber: 0, sodium: 2 },
    nutritionalScore: 10, tags: ["bebida", "hidratacion"] },
  { name: "CafÃ© negro", brand: "", servingSize: 200, servingUnit: "ml", category: "search",
    nutritionPer100g: { calories: 2, protein: 0.3, fat: 0, saturatedFat: 0, carbs: 0, sugar: 0, fiber: 0, sodium: 2 },
    nutritionalScore: 9, tags: ["bebida", "cafeina"] },
  { name: "Cerveza", brand: "", servingSize: 330, servingUnit: "ml", category: "search",
    nutritionPer100g: { calories: 43, protein: 0.5, fat: 0, saturatedFat: 0, carbs: 3.6, sugar: 0, fiber: 0, sodium: 4 },
    nutritionalScore: 3, tags: ["bebida", "alcohol"] },
  { name: "Vino tinto", brand: "", servingSize: 150, servingUnit: "ml", category: "search",
    nutritionPer100g: { calories: 85, protein: 0.1, fat: 0, saturatedFat: 0, carbs: 2.6, sugar: 0.6, fiber: 0, sodium: 4 },
    nutritionalScore: 4, tags: ["bebida", "alcohol"] },

  // Procesados
  { name: "Galletitas de agua", brand: "", servingSize: 30, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 415, protein: 10, fat: 9, saturatedFat: 4, carbs: 72, sugar: 8, fiber: 4, sodium: 700 },
    nutritionalScore: 4.5, tags: ["snack", "galletita"] },
  { name: "Barrita de cereal", brand: "", servingSize: 25, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 420, protein: 8, fat: 12, saturatedFat: 5, carbs: 68, sugar: 30, fiber: 6, sodium: 150 },
    nutritionalScore: 4.5, tags: ["snack", "barrita"] },
  { name: "Yogur con sabor", brand: "", servingSize: 125, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 90, protein: 3, fat: 2.5, saturatedFat: 1.6, carbs: 14, sugar: 12, fiber: 0, sodium: 45 },
    nutritionalScore: 4.5, tags: ["lacteo", "azucar"] },
  { name: "Jamon cocido", brand: "", servingSize: 50, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 145, protein: 20, fat: 6, saturatedFat: 2, carbs: 2, sugar: 1, fiber: 0, sodium: 1000 },
    nutritionalScore: 5.5, tags: ["embutido", "proteina"] },
  { name: "Chocolate amargo 70%", brand: "", servingSize: 30, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 598, protein: 7.8, fat: 43, saturatedFat: 24, carbs: 46, sugar: 24, fiber: 11, sodium: 20 },
    nutritionalScore: 5.5, tags: ["dulce", "cacao"] },
  { name: "Helado de crema", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 207, protein: 3.5, fat: 11, saturatedFat: 6.8, carbs: 24, sugar: 21, fiber: 0.7, sodium: 80 },
    nutritionalScore: 2.5, tags: ["dulce", "postre"] },
  { name: "Papas fritas", brand: "", servingSize: 30, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 536, protein: 7, fat: 35, saturatedFat: 4.5, carbs: 53, sugar: 1.3, fiber: 4.4, sodium: 525 },
    nutritionalScore: 2.5, tags: ["snack", "frito"] },

  // Productos con cÃ³digo de barras (Argentina)
  { name: "Yogur SerenÃ­sima Firme", brand: "SerenÃ­sima", barcode: "7790387012535", servingSize: 190, servingUnit: "g", category: "barcode",
    nutritionPer100g: { calories: 74, protein: 3.8, fat: 2.8, saturatedFat: 1.8, carbs: 8.5, sugar: 8.5, fiber: 0, sodium: 50 },
    nutritionalScore: 6, tags: ["lacteo", "yogur"] },
  { name: "Leche Larga Vida Entera La SerenÃ­sima", brand: "La SerenÃ­sima", barcode: "7790070001562", servingSize: 200, servingUnit: "ml", category: "barcode",
    nutritionPer100g: { calories: 62, protein: 3.2, fat: 3.3, saturatedFat: 1.9, carbs: 4.7, sugar: 4.7, fiber: 0, sodium: 45 },
    nutritionalScore: 7, tags: ["lacteo", "leche"] },
  { name: "Galletitas de agua Manera", brand: "Manera", barcode: "7794000241866", servingSize: 35, servingUnit: "g", category: "barcode",
    nutritionPer100g: { calories: 412, protein: 10, fat: 8.5, saturatedFat: 3.5, carbs: 72, sugar: 6, fiber: 4, sodium: 680 },
    nutritionalScore: 5, tags: ["galletita", "snack"] },
  { name: "Coca-Cola ClÃ¡sica", brand: "Coca-Cola", barcode: "7790895000788", servingSize: 350, servingUnit: "ml", category: "barcode",
    nutritionPer100g: { calories: 42, protein: 0, fat: 0, saturatedFat: 0, carbs: 10.6, sugar: 10.6, fiber: 0, sodium: 3 },
    nutritionalScore: 1.5, tags: ["bebida", "gaseosa", "azucar"] },
  { name: "Agua mineral Villavicencio", brand: "Villavicencio", barcode: "7790310481934", servingSize: 500, servingUnit: "ml", category: "barcode",
    nutritionPer100g: { calories: 0, protein: 0, fat: 0, saturatedFat: 0, carbs: 0, sugar: 0, fiber: 0, sodium: 1 },
    nutritionalScore: 10, tags: ["bebida", "agua"] },
  { name: "AtÃºn Desmenuzable en Aceite La Campagnola", brand: "La Campagnola", barcode: "7790060000126", servingSize: 90, servingUnit: "g", category: "barcode",
    nutritionPer100g: { calories: 190, protein: 22, fat: 11, saturatedFat: 1.8, carbs: 0, sugar: 0, fiber: 0, sodium: 300 },
    nutritionalScore: 6.5, tags: ["pescado", "enlatado", "proteina"] },
  { name: "Arroz Gallo Oro", brand: "Gallo", barcode: "7790433000021", servingSize: 60, servingUnit: "g", category: "barcode",
    nutritionPer100g: { calories: 360, protein: 7.2, fat: 0.7, saturatedFat: 0.2, carbs: 80, sugar: 0.4, fiber: 1, sodium: 2 },
    nutritionalScore: 6, tags: ["arroz", "grano"] },
  { name: "Yerba Mate Playadito", brand: "Playadito", barcode: "7797082100241", servingSize: 50, servingUnit: "g", category: "barcode",
    nutritionPer100g: { calories: 170, protein: 6.5, fat: 1.2, saturatedFat: 0.5, carbs: 30, sugar: 0, fiber: 15, sodium: 5 },
    nutritionalScore: 7, tags: ["mate", "infusion"] },
  { name: "Fideos Marolio", brand: "Marolio", barcode: "7798020000371", servingSize: 80, servingUnit: "g", category: "barcode",
    nutritionPer100g: { calories: 360, protein: 12, fat: 1.5, saturatedFat: 0.3, carbs: 72, sugar: 2, fiber: 3, sodium: 5 },
    nutritionalScore: 5.5, tags: ["pasta"] },
  { name: "CafÃ© InstantÃ¡neo La Virginia", brand: "La Virginia", barcode: "7790895001785", servingSize: 2, servingUnit: "g", category: "barcode",
    nutritionPer100g: { calories: 350, protein: 12, fat: 0, saturatedFat: 0, carbs: 70, sugar: 0, fiber: 0, sodium: 50 },
    nutritionalScore: 7.5, tags: ["cafe", "bebida"] },
  { name: "Queso CremÃ³n La SerenÃ­sima", brand: "La SerenÃ­sima", barcode: "7790070000015", servingSize: 30, servingUnit: "g", category: "barcode",
    nutritionPer100g: { calories: 300, protein: 20, fat: 24, saturatedFat: 15, carbs: 1.5, sugar: 1, fiber: 0, sodium: 600 },
    nutritionalScore: 5, tags: ["lacteo", "queso"] },
  { name: "Salsa de Tomate La Campagnola", brand: "La Campagnola", barcode: "7790060000423", servingSize: 100, servingUnit: "g", category: "barcode",
    nutritionPer100g: { calories: 38, protein: 1.5, fat: 0.2, saturatedFat: 0, carbs: 8, sugar: 5, fiber: 1.5, sodium: 380 },
    nutritionalScore: 7, tags: ["salsa", "tomate"] },
  { name: "Granola Granix", brand: "Granix", barcode: "7790310000524", servingSize: 50, servingUnit: "g", category: "barcode",
    nutritionPer100g: { calories: 430, protein: 10, fat: 14, saturatedFat: 3, carbs: 66, sugar: 20, fiber: 8, sodium: 40 },
    nutritionalScore: 6, tags: ["granola", "desayuno"] },
  { name: "Jugo Baggio Naranja", brand: "Baggio", barcode: "7790050000297", servingSize: 250, servingUnit: "ml", category: "barcode",
    nutritionPer100g: { calories: 48, protein: 0.5, fat: 0, saturatedFat: 0, carbs: 11, sugar: 11, fiber: 0, sodium: 5 },
    nutritionalScore: 4, tags: ["jugo", "bebida", "azucar"] },

  // Jugos y bebidas
  { name: "Jugo Cepita Naranja", brand: "Cepita", barcode: "7790483000371", servingSize: 250, servingUnit: "ml", category: "barcode",
    nutritionPer100g: { calories: 47, protein: 0.5, fat: 0, saturatedFat: 0, carbs: 11, sugar: 11, fiber: 0, sodium: 5 },
    nutritionalScore: 4, tags: ["jugo", "bebida", "azucar"] },
  { name: "Jugo Baggio Multifruta", brand: "Baggio", barcode: "7790050000051", servingSize: 250, servingUnit: "ml", category: "barcode",
    nutritionPer100g: { calories: 44, protein: 0.5, fat: 0, saturatedFat: 0, carbs: 10.5, sugar: 10.5, fiber: 0, sodium: 5 },
    nutritionalScore: 4, tags: ["jugo", "bebida", "azucar"] },
  { name: "Agua saborizada Levite", brand: "Levite", barcode: "7790472010009", servingSize: 500, servingUnit: "ml", category: "barcode",
    nutritionPer100g: { calories: 24, protein: 0, fat: 0, saturatedFat: 0, carbs: 6, sugar: 6, fiber: 0, sodium: 5 },
    nutritionalScore: 5, tags: ["bebida", "agua saborizada"] },
  { name: "Coca-Cola Light", brand: "Coca-Cola", barcode: "7790895000291", servingSize: 350, servingUnit: "ml", category: "barcode",
    nutritionPer100g: { calories: 0.5, protein: 0, fat: 0, saturatedFat: 0, carbs: 0, sugar: 0, fiber: 0, sodium: 5 },
    nutritionalScore: 3, tags: ["bebida", "gaseosa", "diet"] },
  { name: "Jugo de naranja natural", brand: "", servingSize: 250, servingUnit: "ml", category: "search",
    nutritionPer100g: { calories: 45, protein: 0.7, fat: 0.2, saturatedFat: 0, carbs: 10, sugar: 9, fiber: 0.2, sodium: 1 },
    nutritionalScore: 6, tags: ["jugo", "bebida", "natural"] },
  { name: "Limonada natural", brand: "", servingSize: 250, servingUnit: "ml", category: "search",
    nutritionPer100g: { calories: 25, protein: 0.1, fat: 0, saturatedFat: 0, carbs: 8, sugar: 7, fiber: 0.1, sodium: 1 },
    nutritionalScore: 6.5, tags: ["jugo", "bebida", "natural"] },
  { name: "Gaseosa cola", brand: "", servingSize: 350, servingUnit: "ml", category: "search",
    nutritionPer100g: { calories: 42, protein: 0, fat: 0, saturatedFat: 0, carbs: 10.6, sugar: 10.6, fiber: 0, sodium: 3 },
    nutritionalScore: 1.5, tags: ["bebida", "gaseosa", "azucar"] },
  { name: "Gaseosa light", brand: "", servingSize: 350, servingUnit: "ml", category: "search",
    nutritionPer100g: { calories: 1, protein: 0, fat: 0, saturatedFat: 0, carbs: 0.2, sugar: 0, fiber: 0, sodium: 5 },
    nutritionalScore: 3.5, tags: ["bebida", "gaseosa", "diet"] },

  // Alfajores
  { name: "Alfajor Guaymallén", brand: "Guaymallén", barcode: "7790271000333", servingSize: 30, servingUnit: "g", category: "barcode",
    nutritionPer100g: { calories: 450, protein: 5, fat: 17, saturatedFat: 8, carbs: 68, sugar: 40, fiber: 2, sodium: 150 },
    nutritionalScore: 2, tags: ["alfajor", "dulce"] },
  { name: "Alfajor Jorgito", brand: "Jorgito", barcode: "7790080001035", servingSize: 30, servingUnit: "g", category: "barcode",
    nutritionPer100g: { calories: 480, protein: 6, fat: 20, saturatedFat: 9, carbs: 68, sugar: 42, fiber: 2, sodium: 120 },
    nutritionalScore: 2, tags: ["alfajor", "dulce"] },
  { name: "Alfajor Capitan del Espacio", brand: "Capitan del Espacio", barcode: "7790316000993", servingSize: 35, servingUnit: "g", category: "barcode",
    nutritionPer100g: { calories: 460, protein: 5, fat: 18, saturatedFat: 8, carbs: 70, sugar: 45, fiber: 2, sodium: 100 },
    nutritionalScore: 2, tags: ["alfajor", "dulce"] },
  { name: "Alfajor Águila", brand: "Águila", barcode: "7790070001296", servingSize: 30, servingUnit: "g", category: "barcode",
    nutritionPer100g: { calories: 470, protein: 6, fat: 19, saturatedFat: 9, carbs: 67, sugar: 45, fiber: 2.5, sodium: 80 },
    nutritionalScore: 2, tags: ["alfajor", "dulce", "chocolate"] },
  { name: "Alfajor triple", brand: "", servingSize: 40, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 470, protein: 5, fat: 19, saturatedFat: 9, carbs: 69, sugar: 43, fiber: 2, sodium: 130 },
    nutritionalScore: 2, tags: ["alfajor", "dulce"] },
  { name: "Alfajor de maicena", brand: "", servingSize: 40, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 420, protein: 5, fat: 14, saturatedFat: 6, carbs: 70, sugar: 45, fiber: 1.5, sodium: 180 },
    nutritionalScore: 3, tags: ["alfajor", "dulce"] },

  // Golosinas
  { name: "Chocolate con leche", brand: "", servingSize: 30, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 530, protein: 7, fat: 30, saturatedFat: 18, carbs: 58, sugar: 52, fiber: 3, sodium: 80 },
    nutritionalScore: 2.5, tags: ["golosina", "dulce", "chocolate"] },
  { name: "Chocolate Águila", brand: "Águila", barcode: "7790070001005", servingSize: 30, servingUnit: "g", category: "barcode",
    nutritionPer100g: { calories: 540, protein: 6, fat: 32, saturatedFat: 19, carbs: 57, sugar: 55, fiber: 3, sodium: 60 },
    nutritionalScore: 2, tags: ["golosina", "dulce", "chocolate"] },
  { name: "Chocolate blanco", brand: "", servingSize: 30, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 540, protein: 6, fat: 32, saturatedFat: 20, carbs: 59, sugar: 57, fiber: 0, sodium: 90 },
    nutritionalScore: 1.5, tags: ["golosina", "dulce", "chocolate"] },
  { name: "Gomitas Mogul", brand: "Mogul", barcode: "7790070001036", servingSize: 50, servingUnit: "g", category: "barcode",
    nutritionPer100g: { calories: 340, protein: 6, fat: 0.2, saturatedFat: 0, carbs: 77, sugar: 60, fiber: 0, sodium: 50 },
    nutritionalScore: 1.5, tags: ["golosina", "gomitas", "dulce"] },
  { name: "Gomitas", brand: "", servingSize: 50, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 340, protein: 6, fat: 0.2, saturatedFat: 0, carbs: 77, sugar: 60, fiber: 0, sodium: 50 },
    nutritionalScore: 1.5, tags: ["golosina", "gomitas", "dulce"] },
  { name: "Turrón Arcor", brand: "Arcor", barcode: "7790170119000", servingSize: 28, servingUnit: "g", category: "barcode",
    nutritionPer100g: { calories: 420, protein: 6, fat: 13, saturatedFat: 5, carbs: 70, sugar: 60, fiber: 2, sodium: 100 },
    nutritionalScore: 2.5, tags: ["golosina", "dulce"] },
  { name: "Turrón", brand: "", servingSize: 28, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 420, protein: 6, fat: 13, saturatedFat: 5, carbs: 70, sugar: 60, fiber: 2, sodium: 100 },
    nutritionalScore: 2.5, tags: ["golosina", "dulce"] },
  { name: "Mantecol", brand: "", servingSize: 40, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 470, protein: 9, fat: 20, saturatedFat: 6, carbs: 65, sugar: 50, fiber: 3, sodium: 60 },
    nutritionalScore: 2.5, tags: ["golosina", "dulce"] },
  { name: "Rocklets", brand: "Arcor", barcode: "7790070001043", servingSize: 20, servingUnit: "g", category: "barcode",
    nutritionPer100g: { calories: 500, protein: 5, fat: 23, saturatedFat: 12, carbs: 68, sugar: 60, fiber: 2, sodium: 40 },
    nutritionalScore: 1.5, tags: ["golosina", "dulce", "chocolate"] },
  { name: "Caramelos", brand: "", servingSize: 10, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 400, protein: 0, fat: 0.2, saturatedFat: 0, carbs: 98, sugar: 90, fiber: 0, sodium: 20 },
    nutritionalScore: 1, tags: ["golosina", "caramelo"] },
  { name: "Chicles", brand: "", servingSize: 5, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 250, protein: 0, fat: 0, saturatedFat: 0, carbs: 70, sugar: 60, fiber: 0, sodium: 5 },
    nutritionalScore: 1, tags: ["golosina", "chicle"] },
  { name: "Chupetines", brand: "", servingSize: 15, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 400, protein: 0, fat: 0.2, saturatedFat: 0, carbs: 98, sugar: 90, fiber: 0, sodium: 20 },
    nutritionalScore: 1, tags: ["golosina", "dulce"] },
  { name: "Galletitas rellenas", brand: "", servingSize: 30, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 480, protein: 5, fat: 20, saturatedFat: 10, carbs: 68, sugar: 30, fiber: 2, sodium: 300 },
    nutritionalScore: 2, tags: ["golosina", "galletita", "dulce"] },
  { name: "Chizitos", brand: "", servingSize: 30, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 530, protein: 5, fat: 30, saturatedFat: 5, carbs: 60, sugar: 3, fiber: 2, sodium: 700 },
    nutritionalScore: 1.5, tags: ["snack", "salado"] },
  { name: "Palitos salados", brand: "", servingSize: 30, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 420, protein: 10, fat: 8, saturatedFat: 3, carbs: 75, sugar: 2, fiber: 3, sodium: 800 },
    nutritionalScore: 3, tags: ["snack", "salado"] },
  { name: "Helado de agua", brand: "", servingSize: 100, servingUnit: "g", category: "search",
    nutritionPer100g: { calories: 110, protein: 0, fat: 0, saturatedFat: 0, carbs: 28, sugar: 25, fiber: 0, sodium: 10 },
    nutritionalScore: 3, tags: ["postre", "dulce"] },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  const Food = mongoose.connection.db.collection("foods");

  const existing = await Food.countDocuments({});
  if (existing > 0 && !process.argv.includes("--force")) {
    console.log(`Ya hay ${existing} alimentos en la base. No se duplican.`);
    console.log("Usá: node seed/foods.js --force para reemplazar.");
    process.exit(0);
  }

  if (process.argv.includes("--force")) {
    await Food.deleteMany({});
    console.log("Base de alimentos reemplazada (--force).");
  }

  await Food.insertMany(foods);
  console.log(`${foods.length} alimentos cargados correctamente.`);
  process.exit(0);
}

if (require.main === module) {
  seed();
}

module.exports = { foods };

